### DISCUSSION TITLE
postgres fixtures sequence

### DISCUSSION THREAD

**Discussion by evilchown755** [lamoda/gonkey#214] [Q&A]
Добрый день!
Написал тест, используя фикстуры (создаю запись "библиотека" к примеру library_id = 1), для дальнешего тестирования API
Но тест не проходит, так как не совпадают id.
Подскажите пожалуйста, зачем нужна функция: https://github.com/lamoda/gonkey/blob/cd7d8158ff2490729282d2b071d8f7f959e1bd37/fixtures/postgres/postgres.go#L227 , так как она меняет в таблицах ``sequence``.
Пример:
```yaml
- name: CREATE book
  method: POST
  path: /api/v1/library/1/book
  fixtures:
    - library-fixture.yaml
  request: |
    {
      "name": "Test book name"
    }
  response:
    200: |
      {
        "id": 1,
        "library_id": 1,
     	"name": "Test book name"
      }
```

```
Response:
     Status: 200 OK
       Body:
{"id":2, "library_id":1, "name": "Test book name"}



     Result: ERRORS!

Errors:

1) at path $.id values do not match:
     expected: 1
       actual: 2
```

**Comment by leorush** [comment]
Код функции вот [тут](https://github.com/lamoda/gonkey/blob/cd7d8158ff2490729282d2b071d8f7f959e1bd37/fixtures/postgres/postgres.go#L335). 
Нужна для сброса последовательностей. Иначе после каждого теста id будет больше. 
Обычно мы перед загрузкой фикстур, загружаем особую фискстуру с чистой базой. 
fixtures/empty_books_db.yml

```#
tables:
  books: []

**Reply by evilchown755** [reply]
Спасибо за пояснения, да - саму функцию смотрел - но она вызывается всегда когда используются фикстуры.
Сначала чиститься база, затем в этой же транзакции сразу изменяется ``sequence`` у всех таблиц, и на момент моего теста - где я добавляю книгу по API - создается запись с ID = 2...
Вот так делал:
```yaml
- name: CREATE book
  method: POST
  path: /api/v1/library/1/book
  fixtures:
    - library-fixture.yaml
    - empty_books_db.yaml
  request: |
    {
      "name": "Test book name"
    }
  response:
    200: |
      {
        "id": 1,
        "library_id": 1,
     	"name": "Test book name"
      }
```
Таким образом - если я добавляю фикстуру очистки - все равно - будет вызвана эта функция и изменит ``sequence``.
На всякий случай прилагаю DEBUG:
```
=== RUN   CREATE book
Loading ./tests/fixtures/library-fixture.yaml
Populating ref dummy_add_library as {"$extend":"dummy_library","name":"First library"} from template
Loading ./tests/fixtures/empty_books_db.yaml
Issuing SQL: TRUNCATE TABLE "preferences"."libraries","preferences"."books" CASCADE
Issuing SQL: INSERT INTO "preferences"."libraries" AS row ("name") VALUES ('First library') RETURNING row_to_json(row)
Issuing SQL: 
DO $$
DECLARE
    r record;
BEGIN
    FOR r IN (
        SELECT 'SELECT SETVAL(' || quote_literal(quote_ident(seq_ns.nspname) || '.' || quote_ident(seq.relname))
            || ', COALESCE(MAX(' || quote_ident(col.attname) || '), 1) ) FROM '
            || quote_ident(tbl_ns.nspname) || '.' || quote_ident(tbl.relname) AS q
        FROM pg_class seq
            JOIN pg_namespace seq_ns ON (seq.relnamespace = seq_ns.oid)
            JOIN pg_depend dep ON (dep.objid = seq.oid)
            JOIN pg_class tbl ON (dep.refobjid = tbl.oid)
            JOIN pg_namespace tbl_ns ON (tbl.relnamespace = tbl_ns.oid)
            JOIN pg_attribute col ON (col.attrelid = tbl.oid AND dep.refobjsubid = col.attnum)
        WHERE
            seq.relkind = 'S'
        ORDER BY seq.relname
    ) LOOP
        EXECUTE r.q;
    END LOOP;
END$$


Name: CREATE book
Description: No description
File: ./tests/cases/10_books.gonkey.yaml

Request:
     Method: POST
       Path: /api/v1/library/1/book
      Query: 
       Body:
        {
          "name": "Test book name"
        }

Response:
     Status: 200 OK
       Body:
{"id":2, "library_id":1, "name": "Test book name"}

Result: ERRORS!

Errors:

1) at path $.id values do not match:
     expected: 1
       actual: 2


    --- FAIL: CREATE book (0.16s)


```

**Comment by leorush** [comment]
Наоборот, пустую фикстуру до основной. Там будет truncate. (Хотя и так он будет вызван раньше чем фикстура загрузится)
Что в фикстуре у вас?

**Reply by evilchown755** [reply]
Фикстура создания библиотеки
- library-fixture.yaml
```yaml
templates:
  dummy_library:
    name: Dummy Library Name

tables:
  preferences.libraries:
    - $extend: dummy_library
      name: First library
```
Фикстура очистки таблицы книг
- empty_books_db.yaml
```yaml
tables:
  preferences.books: []
```

От перемены мест ничего не изменилось.
Проблема в том что на фикстуру дергается функция изменяющая ``sequence`` для всех таблиц. (не только для таблицы в которую фикстурами добавляю запись, а для всех в БД)
На любые тесты, где есть вставка в БД из-за измененного ``sequence`` - всегда первая запись начинается с ID=2, вот и хочу понять зачем это нужно и может я что то не так делаю.
Может не совсем понятно изъяснил:
По фикстурам все правильно - создается library в таблице с id = 1
А книгу я создаю дергая тестом ручку ``/api/v1/library/1/book`` которая добавляет в БД книгу принадлежащую созданной через фикстуры библиотеке library, но так как был вызван запрос при вызове файла фикстур (в DEBUG режиме видно):
```
Issuing SQL: 
DO $$
DECLARE
    r record;
BEGIN
    FOR r IN (
        SELECT 'SELECT SETVAL(' || quote_literal(quote_ident(seq_ns.nspname) || '.' || quote_ident(seq.relname))
            || ', COALESCE(MAX(' || quote_ident(col.attname) || '), 1) ) FROM '
            || quote_ident(tbl_ns.nspname) || '.' || quote_ident(tbl.relname) AS q
        FROM pg_class seq
            JOIN pg_namespace seq_ns ON (seq.relnamespace = seq_ns.oid)
            JOIN pg_depend dep ON (dep.objid = seq.oid)
            JOIN pg_class tbl ON (dep.refobjid = tbl.oid)
            JOIN pg_namespace tbl_ns ON (tbl.relnamespace = tbl_ns.oid)
            JOIN pg_attribute col ON (col.attrelid = tbl.oid AND dep.refobjsubid = col.attnum)
        WHERE
            seq.relkind = 'S'
        ORDER BY seq.relname
    ) LOOP
        EXECUTE r.q;
    END LOOP;
END$$
```
, то первая запись будет иметь id=2 (во всех таблицах)
Очень интересный инструмент и хотелось бы использовать его в проектах, но вот эта проблема не ясна, хотелось бы разобраться с ней! Можно не проверять ID, но тогда некоторые тесты не актуальны будут (например запрос на получение книги, я в тесте должен в ручку уже писать нужный ID по тесту указанному выше...)(к примеру GET /api/v1/library/1/book/1/, но из за ошибки выше - тест не пройдет и надо тогда писать /api/v1/library/1/book/2, что не логично, так как это первая созданная запись в таблице)
