### ISSUE TITLE
Возможность параметризации заголовов

### ISSUE THREAD

**Issue by VladislavPershin** [lamoda/gonkey#131]
Привет!

Есть ли в gonkey возможность параметризации заголовка?

Кейс следующий - необходимо протестить различные состояния бекенда в зависимости от определенного заголовка(айдишник пользователя).

Я сначала написал скрипт вида:
```headers:
  Content-Type: application/json
  X-UserId:  {{ .userID }}
 ``` 
и потом радостный пошел расписывать секцию cases, но понял, что для headers отсутствует такая секция для cases.

Посоветуйте пожалуйста, как лучше решить проблему параметризации заголовков.

**Comment by Cdayz** [comment]
В gonkey  все переменные которые будут описаны в cases для requestArgs так же применяются и на заголовки, пример:

```yaml
- name: My test
  method: POST
  path: /api/service/v1/endpoint
  headers:
    Authorization: "{{ .header }}"
  request: >
    {
      "field1": "{{ .value1 }}",
      "field2": "{{ .value2 }}",
    }
  response:
    400: >
      {"code":"BadRequestError"}
  cases:
    - requestArgs:
        header: Test-1
        value1: "non-empty"
        value2: "non-empty"
    - requestArgs:
        header: Test-2
        value1: ""
        value2: "non-empty"

```
