### ISSUE TITLE
Возможность переиспользовать значение из приходящего в мок запроса в ответе мока

### ISSUE THREAD

**Issue by keyclaim** [lamoda/gonkey#141]
Добавить в ответ мока поддержку нотации вида {{ $request.field1.field2 }}, которая позволит подставить в ответ значение полученное из пришедшего запроса.

Пример:
```
strategy: constant
body: >
     {
            "order_nr": "{{ $request.otder_nr }}",
      }
```

**Comment by leorush** [comment]
Также стоит иметь возможность обращаться к данным в запросе к моку не только в последующем ответе но и далее,  возможно стоит добавить сохранение их в переменную по выбору.

**Comment by keyclaim** [comment]
Хорошая идея, я также думал над об этом.
Если в мок приходит несколько запросов(в один или несколько эндпоинтов), то с такой нотацией мы останемся в контексте одного вызова, но не сможем переиспользовать снаружи.
Если же мы хотим вынести это значение, то стоит подумать над другой нотацией.
Например, можно извлекать поле по json-path внутри стратегии и сохранять его в переменные
```
mock:
  calls: 1
  strategy: uriVary
  uris:
    /v1/order.create:
      extractField:
        path: result.order_nr
        variableName: order_nr
```
Над нотацией стоит подумать побольше.
