### ISSUE TITLE
Возможность указывать в качестве request/response файл

### ISSUE THREAD

**Issue by keyclaim** [lamoda/gonkey#143]
Чтобы не ломать обратную совместимость можно добавить новые нотации, либо все же переработать старые.
Эта фича имеет смысл после реализации https://github.com/lamoda/gonkey/issues/142.
Тогда можно будет избавиться от больших json внутри yaml-сценария.
```
requestFromFile:
  file: some_request.json
  overrideParams:
    order[0].amount: 1000.01 
respinseFromFile:
  file: some_respinse.json
  overrideParams:
    order[0].amount: 1000.01 
```
