### ISSUE TITLE
How I can send file by POST?

### ISSUE THREAD

**Issue by devig** [lamoda/gonkey#16]
How I can send file(s) with json fields by POST? (Как отправить файл вместе с json полями POST-ом)

**Comment by luza** [comment]
Currently there is no native way to pass a file, so to achieve that you have to construct the request body by yourself.

According to HTTP standard, you should use multipart/form-data mime type, define a separator and split body in two parts: one for POST parameters, second for the file content.

**Comment by devig** [comment]
Can you show small example?

**Comment by luza** [comment]
I wrote a tiny endpoint in PHP, which dumps request payload:
```php
<?php

header('Content-Type: application/json');
die(json_encode(['post' => $_POST, 'files' => $_FILES]));
```

Here is a Gonkey test scenario for such endpoint:
```yaml
- name: WHEN posting a file MUST return no error
  method: POST
  path: /accept-file.php
  headers:
    Content-Type: multipart/form-data; boundary=XXX
  request: |
    --XXX
    Content-Disposition: form-data; name="form_field_name"

    FormFieldValue
    --XXX
    Content-Disposition: form-data; name="userfile"; filename="filename.txt"
    Content-Type: application/octet-stream

    content of your file...
    --XXX--

  response:
    200: >
        {
          "post": {
            "form_field_name": "FormFieldValue"
          },
          "files": {
            "userfile": {
              "name": "filename.txt",
              "type": "application/octet-stream",
              "error": 0,
              "size": 23
            }
          }
        }
```

While experimenting, I've realised that the submitting file body cannot be binary (as it needs to be defined in YAML), so you can't submit an image for example.
