### ISSUE TITLE
Тестирование Prometheus метрик

### ISSUE THREAD

**Issue by ikramanop** [lamoda/gonkey#161]
Предлагаю в рамках gonkey-тестов тестировать prometheus метрики.
Почти все сервисы такие метрики используют, они важны для мониторинга и отслеживания бизнес-процессов, поэтому необходимо убеждаться в корректности записи таких метрик.

Формат записи может быть следующий.
```yaml
metrics:
  - type: counter
    name: payment_gate_pay_session_results_total
    labels:
      - result: success
      - terminal: TestTerminal
      - vendor: payture
    change: 2
```

Чтобы внедрить тестирование метрик в текущий флоу, необходимо:
- Парсить раздел metrics в определении теста
- Перед тестом делать запрос на /metrics или другой системный эндпоинт, по которому можно получить plaintext представление метрик
- Парсить результат и хранить условную beforeMetric структуру
- Выполнить основное тело теста
- После выполнения запроса и всех проверок повторно сделать запрос на системный эндпоинт, спарсить результат и сравнить с beforeMetric с учётом описанных в теле теста проверок
