### ISSUE TITLE
Добавить возможность объявнять кастомные функции

### ISSUE THREAD

**Issue by fetinin** [lamoda/gonkey#200]
Может возникнуть необходимость генерировать UUID.

У нас уже есть возможность вызывать кастомные функции в шаблонах, например `$matchRegexp`. Было бы классно добавить возможность для тестов регистировать свои кастомные функции.

Перед запуском теста описываешь нужную функцию на Go, регистируешь её в раннере и можешь вызывать внутри тестов. Например так:
```yaml
variables:
  myUUID: $generateUUID4()

response:
  200:
    "{{$myUUID}}"
```
