### ISSUE TITLE
Возможность использования динамический переменных

### ISSUE THREAD

**Issue by redoeyeo** [lamoda/gonkey#210]
Для определенного набора тестов, было бы удобна возможность использовать рандомные переменные (особенно, если была бы возможность брать текущее время), например:
```yaml
- name: Create item
  method: POST
  variables:
    name: "Name-{{timestamp}}"
  path: /api/items/
  request: >
    {
        "name": "{{$name}}"
    }
```
поэтому, вопрос, нет ли сейчас возможности каким-либо образом генерировать данные на лету, и отправлять их внутри запросов?
