### ISSUE TITLE
При добавлении поля `status` в тестовый сценарий, возникает ошибка `panic`.

### ISSUE THREAD

**Issue by ZhikharevAl** [lamoda/gonkey#247]
### Описание проблемы

При добавлении поля `status` в тестовый сценарий, возникает ошибка `panic`.

### Пример тестового сценария

```yaml
tests:
  - name: ...
    method: GET
    status: skipped
    path: /planetary/apod
    query: "api_key={{$API_KEY}}&start_date=2024-06-17"

```

### Ошибка
```bash
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x78 pc=0xa3d9d7]

goroutine 1 [running]:
github.com/lamoda/gonkey/models.(*Result).Passed(...)
        .../go/pkg/mod/github.com/lamoda/gonkey@v1.21.4/models/result.go:73
github.com/lamoda/gonkey/runner.(*ConsoleHandler).HandleTest(0xc00019adc0, {0xc7fcb0?, 0xc0001d9200?}, 0x7fd4d5bc0501?)
       .../go/pkg/mod/github.com/lamoda/gonkey@v1.21.4/runner/console_handler.go:32 +0xd7
github.com/lamoda/gonkey/runner.(*Runner).Run(0xc00013cc00)
        .../go/pkg/mod/github.com/lamoda/gonkey@v1.21.4/runner/runner.go:99 +0x1cd
main.main()
        .../go/pkg/mod/github.com/lamoda/gonkey@v1.21.4/main.go:75 +0x769
```
### Шаги воспроизведения:
1. Запустите тест с использованием status теста.

### Ожидаемое поведение:
Тест должен выполняться успешно без ошибки.

### Фактическое поведение:
При добавлении поля status в тестовый сценарий возникает ошибка panic.

### Дополнительная информация:
Проблема возникает только при добавлении поля status в тестовый сценарий. Без этого поля тест выполняется корректно.

### Среда выполнения:
* Версия Go: 1.22.4
* Версия Gonkey: 1.21.4
* Операционная система: Ubuntu 22.04.3 LTS

**Comment by Mania-c** [comment]
@ZhikharevAl здравствуйте. Мне не удалось воспроизвести ошибку, проблема актуальна ?
Если да, тогда пришлите, пожалуйста, всё содержимое файла "тестового сценария"

**Comment by ZhikharevAl** [comment]
Салют @Mania-c 

---

### Тест

```yaml
- name:
    WHEN an APOD endpoint with the correct `start_date` IS requested, IT SHOULD return
    a range of dates successfully.
  description:
    Test the APOD endpoint with the correct `start_date` to ensure it returns a
    successful response containing a range of dates from https://api.nasa.gov/planetary/apod.
    The response should include data for each date starting from `start_date` up to the
    current date.
  method: GET
  status: skipped
  path: /planetary/apod
  query: "api_key={{$API_KEY}}&start_date=2025-01-30"
  headers:
    Content-Type: application/json
  response:
    200: >
      [{}, {}, {}, {}, {}]
```

---

### Запуск теста
```bash
gonkey -tests=./gonkey/tests/APOD/test_apod_with_start_date.gonkey.yaml -host=https://api.nasa.gov/ -v
```
### Проблема с тестами

1. **Статус `skipped` или `broken`:**  
   Если тест помечен как `skipped` или `broken`, выполнение тестового набора завершается с ошибкой:  
   ```plaintext
   panic: runtime error: invalid memory address or nil pointer dereference
   ```

2. **Статус `focus`:**  
   Если тест помечен как `focus` и в наборе больше одного теста, выполнение завершается с ошибкой, так как все остальные тесты в suite у которых не проставлен статус, будут отмечены как skipped и будут запущены только тесты со статусом focus, согласно документации.
   Если тест только один и помечен как `focus`, он выполняется успешно.

3. **Пустой статус (`status: ""`):**  
   Если статус теста пустой, тест выполняется успешно.

---

### Где падает, а где нет

- **Падает:**  
  - Когда `status: skipped`.  
  - Когда `status: broken`.  
  - Когда `status: focus` и в наборе больше одного теста.

- **Не падает:**  
  - Когда `status: ""` (пустой).  
  - Когда `status: focus` и тест только один в наборе.

---
