### ISSUE TITLE
Новая проверка expectedQuery описана в readme некорректо(ru, eng)

### ISSUE THREAD

**Issue by keyclaim** [lamoda/gonkey#42]
**В readme в примере допущена ошибка**
Example:
```yaml
  ...
  mocks:
    service1:
      requestConstraints:
        # this check will demand that the request contains key1 и key2
        # and the values are key1=value1, key1=value11 и key2=value2. 
        # Keys not mentioned here are omitted while running the check.
        - kind: expectedQuery
          query:  key1=value1&key2=value2&key1=value11
    ...
```
На самом деле в шаблоне используются другие ключи
``` 
     requestConstraints:
       - kind: queryMatches
         expectedQuery: key1=value1&key2=value2&key1=value11
```
